# Generated by Django 6.1.1 on 2026-09-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('sinopsis', models.TextField()),
                ('genero', models.CharField(max_length=60)),
                ('animo', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('estresado', 'Estresado/a'), ('aburrido', 'Aburrido/a'), ('romantico', 'Romántico/a')], max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('emoji', models.CharField(default='🎬', max_length=5)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
